"""change url_photo to photo_url

Revision ID: 852350800966
Revises: 922d408a1ca4
Create Date: 2025-07-14 19:35:50.669439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852350800966'
down_revision = '922d408a1ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=512), nullable=True))
        batch_op.drop_column('url_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_photo', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
