"""Add source and external_id atribute to Recipes in order to use external recipes from an API

Revision ID: 8d79c014ef40
Revises: e6fbc76d35c7
Create Date: 2025-07-13 16:30:24.060188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d79c014ef40'
down_revision = 'e6fbc76d35c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
