"""add image_url to Recipe

Revision ID: 922d408a1ca4
Revises: 8d79c014ef40
Create Date: 2025-07-14 19:32:52.095086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922d408a1ca4'
down_revision = '8d79c014ef40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_photo', sa.String(length=512), nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('photo_filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('photo_filename',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('url_photo')

    # ### end Alembic commands ###
